/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kafka.protobuf.serder

import com.example.tutorial.Msg
import com.google.protobuf.ExtensionRegistryLite
import com.google.protobuf.MessageOrBuilder
import kotlin.test.Test
import kotlin.test.assertTrue

class LibraryTest {
    @Test fun testSomeLibraryMethod() {
        val x = Library()
//        val classUnderTest = Library()
 //       assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'")
    }
}
